In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive

In [ ]:
import os
train_fnames = os.listdir("/content/gdrive/My Drive/CS3244/Train/")
val_fnames = os.listdir("/content/gdrive/My Drive/CS3244/Validation/")
test_fnames = os.listdir("/content/gdrive/My Drive/CS3244/Test/")

In [ ]:
#Read dataframe for only 1 (work on merging all pandas dataframe TBD)
df = pd.concat(map(lambda x: pd.read_csv(f"/content/gdrive/My Drive/CS3244/Train/{x}", header=None), train_fnames), ignore_index=True)
#Drop first column and set col names
df = df.iloc[: , 1:]
df.columns = ["id", "annotations", "text", "hashtag"]
df = df.dropna(subset=['text']).fillna("")
df

,id,annotations,text,hashtag
1,743605077299060737,1384.0,You're my shotgun rider üòÖ https://t.co/F0PQXolmWv,
2,743735645781131264,1384.0,"@pitxapillar much more concisely put, thank you üòÖ",
6,744105058405605376,1384.0,Mirror is life. üòÖ https://t.co/E6iCSwrPPh,
8,748046846384291842,1384.0,@fadhilahrohani1 @aimynadyea please take one o...,
11,747729895845990402,1384.0,RT @Tabather_S: Lmao when NK asked Arnav who h...,
...,...,...,...,...
1595511,7.48068E+17,1392.0,Now that's a #GreatEggcaseHunt! üòç https://t.co...,"[{'start': 13, 'end': 30, 'tag': 'GreatEggcase..."
1595513,7.46279E+17,1392.0,RT @BigglesVapes: An after-review #handcheck üòç...,"[{'start': 34, 'end': 44, 'tag': 'handcheck'},..."
1595514,7.44855E+17,1392.0,@Americooligan thanks üòç,
1595515,7.42991E+17,1392.0,Ari's mom braided my hair üòç,
1595519,7.47122E+17,1392.0,RT @shwetavyas007: @juniorbachchan @JaipurPant...,

In [ ]:
##Number of annotations in train. Should be 20
print(df['annotations'].nunique())

20

In [ ]:
#Get description of annotations, data looks relatively balanced
print(df["annotations"].value_counts())
#Get number of rows with hashtag
print(len(df[df["hashtag"] != ""]))

186.0     31733
1403.0    31293
1389.0    30227
1393.0    30208
1380.0    30035
1381.0    28534
1392.0    28068
830.0     27094
1107.0    26499
1056.0    24235
1394.0    23696
1424.0    23310
1620.0    22718
1138.0    22545
1399.0    21213
1384.0    21051
1397.0    19410
1447.0    19262
1420.0    19033
1446.0    16594
Name: annotations, dtype: int64
54411

In [ ]:
#Removing emoji and hashtag from text
!pip install emoji
import emoji
import re

df_new = df.copy()
def strip_emoji(text):
    new_text =  re.sub(":([^,]*):","",emoji.demojize(text))
    return new_text
  
df_new["text"] = df_new["text"].apply(lambda x: strip_emoji(x))
df_new

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: emoji in /usr/local/lib/python3.7/dist-packages (2.1.0)

,id,annotations,text,hashtag
1,743605077299060737,1384.0,You're my shotgun rider //t.co/F0PQXolmWv,
2,743735645781131264,1384.0,"@pitxapillar much more concisely put, thank you",
6,744105058405605376,1384.0,Mirror is life. //t.co/E6iCSwrPPh,
8,748046846384291842,1384.0,@fadhilahrohani1 @aimynadyea please take one o...,
11,747729895845990402,1384.0,RT @Tabather_S//t.co/iHDyhu7In6,
...,...,...,...,...
1595511,7.48068E+17,1392.0,Now that's a #GreatEggcaseHunt! //t.co/qjUB5zAP6H,"[{'start': 13, 'end': 30, 'tag': 'GreatEggcase..."
1595513,7.46279E+17,1392.0,RT @BigglesVapes//t.co/3cL65WeQ33,"[{'start': 34, 'end': 44, 'tag': 'handcheck'},..."
1595514,7.44855E+17,1392.0,@Americooligan thanks,
1595515,7.42991E+17,1392.0,Ari's mom braided my hair,
1595519,7.47122E+17,1392.0,RT @shwetavyas007,

In [ ]:
#Update hashtag column
from ast import literal_eval
def extract_hashtag(text):
  if text != "":
    lst = [i['tag'] for i in literal_eval(text)]
    return " ".join(lst)
  return text

df_new["hashtag"] = df_new["hashtag"].apply(lambda x: extract_hashtag(x))
#Sanity check
df_new[df_new["hashtag"] != ""]

,id,annotations,text,hashtag
51,744792701363617792,1384.0,Nothing gives me more anxiety than game of thr...,GoT
135,745083460952326144,1384.0,Once the cake got cut the dance floor did too ...,louiswedding goodvibes goodtimes
176,741912132330086400,1384.0,RT @Mickel_70//t.co/0UOZPdbKnK,Tedxbrum PowerofUs beatbox gassed
186,748545009402556416,1384.0,@mark_chan95 yes mark! #laban,laban
265,743425307298783232,1384.0,remember the boner song? #VoteJack,VoteJack
...,...,...,...,...
1595482,7.42988E+17,1392.0,@ColorsTV Guys Show our power again &amp; make...,Aara krishnadasi
1595484,7.46773E+17,1392.0,RT @bryanjlewis17,EURO2016
1595508,7.4327E+17,1392.0,@StVitalCentre favorite thing to do with dad i...,SVCWIW
1595511,7.48068E+17,1392.0,Now that's a #GreatEggcaseHunt! //t.co/qjUB5zAP6H,GreatEggcaseHunt
1595513,7.46279E+17,1392.0,RT @BigglesVapes//t.co/3cL65WeQ33,handcheck HappyFathersDay vape vapelife ejuice...

In [ ]:
#Remove hashtag and links from hashtag from existing text
  
hashtag_df = df_new[df_new["hashtag"] != ""].copy()
hashtag_df["text"] = hashtag_df["text"].apply(lambda x: re.sub(' #([^,]*)', "", x))

#Merge two dataframe
df_v2 = pd.concat([hashtag_df, df_new[df_new["hashtag"] == ""]]).reset_index().drop(columns=['id', 'index'])
df_v2["text"] = df_v2["text"].apply(lambda x: re.sub('//t.co/([^,]*)', "", x))
df_v2

,annotations,text,hashtag
0,1384.0,Nothing gives me more anxiety than game of thr...,GoT
1,1384.0,Once the cake got cut the dance floor did too,louiswedding goodvibes goodtimes
2,1384.0,RT @Mickel_70,Tedxbrum PowerofUs beatbox gassed
3,1384.0,@mark_chan95 yes mark!,laban
4,1384.0,remember the boner song?,VoteJack
...,...,...,...
496753,1392.0,Agape Worshippers their voices are so angelic...,
496754,1392.0,@abike \nHe's a cutie,
496755,1392.0,@Americooligan thanks,
496756,1392.0,Ari's mom braided my hair,
496757,1392.0,RT @shwetavyas007,

In [ ]:
# Download nltk resources
import nltk
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
from nltk.stem.wordnet import WordNetLemmatizer
lem = WordNetLemmatizer()
lem.lemmatize("freezing")

'freezing'

In [ ]:
#Tokenization of the text, use Tweet Tokenizer to remove handles of tweets 
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer 
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.tokenize import TweetTokenizer
import string

tknzr = TweetTokenizer(strip_handles=True, reduce_len=True)
stpwrds = stopwords.words("english")
stpwrds.append("rt")
lem = WordNetLemmatizer()

def preprocess(text):
  remove_tags = " ".join([i for i in text.split() if i[0] != "@"])
  removed_punctuation = "".join([i for i in remove_tags if i not in string.punctuation])
  lower_case = removed_punctuation.lower()
  tokens = tknzr.tokenize(lower_case)
  removed_stopwords = [i for i in tokens if i not in stpwrds]
  lemm_text = [lem.lemmatize(word) for word in removed_stopwords]
  return lemm_text

df_v2["tokens"] = df_v2["text"].apply(lambda x: preprocess(x))
df_v2

,annotations,text,hashtag,tokens
0,1384.0,Nothing gives me more anxiety than game of thr...,GoT,"[nothing, give, anxiety, game, throne]"
1,1384.0,Once the cake got cut the dance floor did too,louiswedding goodvibes goodtimes,"[cake, got, cut, dance, floor]"
2,1384.0,RT @Mickel_70,Tedxbrum PowerofUs beatbox gassed,[]
3,1384.0,@mark_chan95 yes mark!,laban,"[yes, mark]"
4,1384.0,remember the boner song?,VoteJack,"[remember, boner, song]"
...,...,...,...,...
496753,1392.0,Agape Worshippers their voices are so angelic...,,"[agape, worshipper, voice, angelic, god, bless..."
496754,1392.0,@abike \nHe's a cutie,,"[he, cutie]"
496755,1392.0,@Americooligan thanks,,[thanks]
496756,1392.0,Ari's mom braided my hair,,"[aris, mom, braided, hair]"
496757,1392.0,RT @shwetavyas007,,[]

In [ ]:
df_v2["len"] = df_v2["tokens"].apply(lambda x: len(x))
df_v3 = df_v2[df_v2["len"] != 0]
print(20000 - df_v3["annotations"].value_counts())

1403.0   -6367
1380.0   -6091
1389.0   -5543
186.0    -5215
1393.0   -4634
1381.0   -3368
1392.0   -2423
1107.0   -1447
830.0    -1368
1394.0     241
1424.0    1261
1056.0    1303
1620.0    1920
1399.0    2137
1384.0    2441
1397.0    4028
1138.0    4792
1447.0    4821
1420.0    5089
1446.0    6931
Name: annotations, dtype: int64

In [ ]:
df_v2["tokens"].apply(lambda x: len(x)).value_counts()

0     95266
2     78053
3     61296
1     61259
4     47542
5     36444
6     28298
7     21635
8     17273
9     13557
10    10550
11     8581
12     6302
13     4327
14     2834
15     1657
16      924
17      494
18      269
19       99
20       45
21       24
22       11
23        7
24        6
26        2
27        1
29        1
51        1
Name: tokens, dtype: int64

In [ ]:
df_v2.to_csv("/content/gdrive/My Drive/CS3244/train_preprocessed.csv")

In [ ]:
## Validation
df = pd.concat(map(lambda x: pd.read_csv(f"/content/gdrive/My Drive/CS3244/Validation/{x}", header=None), val_fnames), ignore_index=True)
#Drop first column and set col names
df = df.iloc[: , 1:]
df.columns = ["id", "annotations", "text", "hashtag"]
df = df.dropna(subset=['text']).fillna("")
df

,id,annotations,text,hashtag
3,742480792606105601,1397,I look like bansing castu üòí https://t.co/nLsJV...,
8,746609095818383361,1397,@thegooglefact @UnreveaISecrets I wish that wa...,
9,742062396320141313,1397,@CocoFluff70 That's what gets me. You can't be...,
11,746706663038656512,1397,Exactly!!!!I just killed two mosquitos ..I thi...,
23,748209751620747264,1397,RT @Maaa_uhhh: I hate when you cut somebody of...,
...,...,...,...,...
196266,741880565301841920,1394,@__ClassySassy You pose to be sleep playa. üòè,
196274,747280581159878657,1394,Leo blocked me on Twitter because I called him...,"[{'start': 57, 'end': 75, 'tag': 'SaltyLittleC..."
196280,743569648092864512,1394,Happy bday c u soon @_rachelhowardd üòè https://...,
196281,742257986534551552,1394,RT @x__lav__x: I love the skin im in lol üòè far...,
196282,746523654096191488,1394,When ur @ 1/2 Latino wedding &amp; the DJ pla...,"[{'start': 49, 'end': 60, 'tag': 'SuenaElRio'}]"

In [ ]:
##Number of annotations in train. Should be 20
print("number of annotation", df['annotations'].nunique())
#Get description of annotations, data looks relatively balanced
print(df["annotations"].value_counts())
#Get number of rows with hashtag
print(len(df[df["hashtag"] != ""]))

number of annotation 20
1403    4252
186     4179
1389    3747
1392    3718
1381    3602
830     3485
1107    3344
1380    3232
1393    3149
1056    2983
1424    2957
1138    2904
1620    2889
1384    2702
1394    2540
1420    2438
1447    2404
1397    2376
1399    2251
1446    2014
Name: annotations, dtype: int64
6770

In [ ]:
df_new = df.copy()
df_new["text"] = df_new["text"].apply(lambda x: strip_emoji(x))
df_new["hashtag"] = df_new["hashtag"].apply(lambda x: extract_hashtag(x))
hashtag_df = df_new[df_new["hashtag"] != ""].copy()
hashtag_df["text"] = hashtag_df["text"].apply(lambda x: re.sub(' #([^,]*)', "", x))
df_v2 = pd.concat([hashtag_df, df_new[df_new["hashtag"] == ""]]).reset_index().drop(columns=['id', 'index'])
df_v2["text"] = df_v2["text"].apply(lambda x: re.sub('//t.co/([^,]*)', "", x))
df_v2["tokens"] = df_v2["text"].apply(lambda x: preprocess(x))
df_v2

,annotations,text,hashtag,tokens
0,1397,Still no knife,CSGO,"[still, knife]"
1,1397,""" Tristan Thompson """,PutSomeRespeckOnIt,"[tristan, thompson]"
2,1397,RT @SoScarlett69\nAny pathetic losers want to ...,sissy chastity loser pindick,"[pathetic, loser, want, get, locked]"
3,1397,RT @Gilroy_Emily,pcya Stuckinbed,[]
4,1397,Why Everything I love come on Sundays. The day...,Mafia3,"[everything, love, come, sunday, day, work]"
...,...,...,...,...
61161,1394,Coming Soon,,"[coming, soon]"
61162,1394,@camthebear couldn't be missed,,"[couldnt, missed]"
61163,1394,@__ClassySassy You pose to be sleep playa.,,"[pose, sleep, playa]"
61164,1394,Happy bday c u soon @_rachelhowardd,,"[happy, bday, c, u, soon]"
61165,1394,RT @x__lav__x,,[]

In [ ]:
df_v2["len"] = df_v2["tokens"].apply(lambda x: len(x))
df_v3 = df_v2[df_v2["len"] != 0]
print(2500-df_v3["annotations"].value_counts())

1403   -1126
186     -818
1389    -641
1392    -455
1381    -433
1380    -334
830     -227
1107    -214
1393     -63
1424     115
1056     185
1620     188
1384     243
1394     363
1397     545
1138     547
1420     593
1399     621
1447     628
1446     903
Name: annotations, dtype: int64

In [ ]:
print(df_v3["annotations"].value_counts())

1403    3626
186     3318
1389    3141
1392    2955
1381    2933
1380    2834
830     2727
1107    2714
1393    2563
1424    2385
1056    2315
1620    2312
1384    2257
1394    2137
1397    1955
1138    1953
1420    1907
1399    1879
1447    1872
1446    1597
Name: annotations, dtype: int64

In [ ]:
df_v2.to_csv("/content/gdrive/My Drive/CS3244/validation_preprocessed.csv")

In [ ]:
## Test
df = pd.concat(map(lambda x: pd.read_csv(f"/content/gdrive/My Drive/CS3244/Test/{x}", header=None), test_fnames), ignore_index=True)
#Drop first column and set col names
df = df.iloc[: , 1:]
df.columns = ["id", "annotations", "text", "hashtag"]
df = df.dropna(subset=['text']).fillna("")
df

,id,annotations,text,hashtag
0,742430006798864386,1397,Waiting for my meeting with Occupational Healt...,
2,742166067389300736,1397,RT @No_Bitch_No: Seriously made me cryüòíÔ∏è https...,
8,747543740156350464,1397,"Ahan, that was 13th of march now RT @samuel__...",
10,743963364137836545,1397,@OTOrtiz_ dawg I didn't see you until like 3am...,
14,741379442912559104,1397,With how this traffic is going here I think I'...,
...,...,...,...,...
198995,746515378453479428,1394,RT @BruceWayn3_: @__kayshaaa yea that too üòè,
198997,746491954553192449,1394,RT @sarismenor: @sw33t_tTexas Tina would you m...,
198998,741438862849757184,1394,Yup! I know ADs who went to the JaDine concert...,
198999,747188377649176576,1394,Yep yep üòè https://t.co/FuFXxAukLY,
199002,744905085524709377,1394,Coming Soon üòè https://t.co/8YfOGxOr7J,

In [ ]:
##Number of annotations in train. Should be 20
print("number of annotation", df['annotations'].nunique())
#Get description of annotations, data looks relatively balanced
print(df["annotations"].value_counts())
#Get number of rows with hashtag
print(len(df[df["hashtag"] != ""]))

number of annotation 20
1403    3979
186     3977
1389    3769
1392    3671
1381    3652
830     3445
1107    3354
1393    3321
1380    3266
1424    3191
1620    3107
1056    3035
1138    2892
1447    2737
1384    2658
1420    2553
1394    2505
1397    2405
1446    2273
1399    2181
Name: annotations, dtype: int64
6791

In [ ]:
df_new = df.copy()
df_new["text"] = df_new["text"].apply(lambda x: strip_emoji(x))
df_new["hashtag"] = df_new["hashtag"].apply(lambda x: extract_hashtag(x))
hashtag_df = df_new[df_new["hashtag"] != ""].copy()
hashtag_df["text"] = hashtag_df["text"].apply(lambda x: re.sub(' #([^,]*)', "", x))
df_v2 = pd.concat([hashtag_df, df_new[df_new["hashtag"] == ""]]).reset_index().drop(columns=['id', 'index'])
df_v2["text"] = df_v2["text"].apply(lambda x: re.sub('//t.co/([^,]*)', "", x))
df_v2["tokens"] = df_v2["text"].apply(lambda x: preprocess(x))
df_v2

,annotations,text,hashtag,tokens
0,1397,I thought (hoped) Drogon had eaten up Dany,GoT,"[thought, hoped, drogon, eaten, dany]"
1,1397,when thou art 'dead' and ev'ryone thinkests th...,ImStillAlive,"[thou, art, dead, evryone, thinkests, barge, t..."
2,1397,Anyone wanna play online? \n#bored,bored,"[anyone, wanna, play, online, bored]"
3,1397,James why tf are you crying? Colombia advanced,PERvCOL,"[james, tf, cry, colombia, advanced]"
4,1397,I see the shooting in,Orlando,"[see, shooting]"
...,...,...,...,...
61966,1394,RT @BruceWayn3_,,[]
61967,1394,RT @sarismenor,,[]
61968,1394,Yup! I know ADs who went to the JaDine concert,,"[yup, know, ad, went, jadine, concert]"
61969,1394,Yep yep,,"[yep, yep]"
61970,1394,Coming Soon,,"[coming, soon]"

In [ ]:
df_v2["len"] = df_v2["tokens"].apply(lambda x: len(x))
df_v3 = df_v2[df_v2["len"] != 0]
print(2500-df_v3["annotations"].value_counts())

1403   -872
1389   -711
186    -638
1381   -487
1392   -453
1380   -330
1393   -214
830    -199
1107   -185
1424    -92
1620     15
1056    119
1384    278
1447    340
1394    433
1397    506
1420    514
1138    519
1446    683
1399    704
Name: annotations, dtype: int64

In [ ]:
print(df_v3["annotations"].value_counts())

1403    3372
1389    3211
186     3138
1381    2987
1392    2953
1380    2830
1393    2714
830     2699
1107    2685
1424    2592
1620    2485
1056    2381
1384    2222
1447    2160
1394    2067
1397    1994
1420    1986
1138    1981
1446    1817
1399    1796
Name: annotations, dtype: int64

In [ ]:
df_v2.to_csv("/content/gdrive/My Drive/CS3244/test_preprocessed.csv")